title: Yinzi Xin's Research Website
url: "https://yinzi-xin.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "cv.pdf"